# data encoding
## Label-encoding
sklearn.preprocessing의 LabelEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# LabelEncoder() 객체 생성 후 fit 과 transform으로 레이블 인코딩을 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값', labels)

LabelEncoder의 객체의 classes_ 속성값을 이용하면 어떤 숫자로 인코딩 했는지 알 수 있다.

In [3]:
print('인코딩 클래스', encoder.classes_)

인코딩 클래스 ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


inverse_transform을 사용하면 인코딩 값을 디코딩할 수 있다.

In [6]:
print('디코딩 원본값', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값 ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


## One-hot encoding
sklearn.preprocessing 의 OneHotEncoder

In [12]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 2차원 데이터로 변환
items = np.array(items).reshape(-1,1)

#one hot encoding
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

#one_hot encoder로 변환한 결과 = 희소행렬임 -> toarray로 밀집행렬로 변환
print('원 핫 인코딩 데이터', oh_labels.toarray())
print('원 핫 인코딩 데이터 차원', oh_labels.shape)

원 핫 인코딩 데이터 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원 핫 인코딩 데이터 차원 (8, 6)


In [14]:
oh_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [19]:
# 판다스 이용
import pandas as pd

df= pd.DataFrame({'items' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
})

pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0