## CH3. Numpy

- 3.1 넘파이 라이브러리 가져오기
- 3.2 넘파이와 리스트
- 3.3 넘파이 벡터 생성
- 3.4 넘파이 행렬 생성
- 3.5 넘파이 산술연산
- 3.6 넘파이 형 변환
- 3.7 넘파이 브로드캐스트
- 3.8 넘파이 전치행렬
- 3.9 넘파이 행렬 곱
- 3.10 행렬 원소 접근
- 3.11 넘파이 이터레이터
- 3.12 넘파이 유용한 함수
- 3.13 정리

### 3.1 넘파이 라이브러리 가져오기

- import numpy as np

In [1]:
import numpy as np

### 3.2 넘파이와 리스트(numpy vs list)

In [3]:
# 예제 3.1 

#리스트 연산
A = [[1,0],[0,1]]
B = [[1,1],[1,1]]
A + B

[[1, 0], [0, 1], [1, 1], [1, 1]]

위와 같은 리스트 연산은 합이 아닌 리스트가 추가된(append) 결과를 반환한다.

In [6]:
#행렬 연산

import numpy as np
A = np.array([[1,0],[0,1]])
B = np.array([[1,1],[1,1]])
A + B


array([[2, 1],
       [1, 2]])

반면 Numpy로 정의된 행렬A, B를 보면 우리가 원하는 행렬 연산 결과를 반환한다.
행렬을 표현, 연산하려면 Numpy를 이용해 행렬을 만들어준다.

**머신러닝과 딥러닝을 구현할 때 다양한 행렬 연산을 하려면 이 점이 무엇보다 중요하다!!**

### 3.3 넘파이 벡터 생성

- np.array() : 넘파이 이용해 1차원 백터 생성
    - np.array()는 리스트를 인수로 받아 배열 형태의 numpy.ndarry 타입을 리턴한다.

- A.shape : 벡터의 형상(shape) 확인
- A.ndim : 벡터의 차원(dimension) 확인

In [15]:
# 예제 3.2 넘파이 벡터 생성, 형상 및 차원 확인

import numpy as np

A = np.array([1,2,3])
B = np.array([4,5,6])
print("A ==", A ,", B ==", B)
print("vector A shape ==", A.shape, ", vector B shape ==", B.shape)
print("vector A dimension ==", A.ndim, ", vector B dimension ==", B.ndim)


A == [1 2 3] , B == [4 5 6]
vector A shape == (3,) , vector B shape == (3,)
vector A dimension == 1 , vector B dimension == 1


### 3.4 넘파이 행렬(matrix, 2차원 배열) 생성

- 벡터를 만들 때와 다르게 행렬에서 1개 ROW 정의 시 np.array() 안에서 다시 대괄호를 사용한다

In [23]:
#예제 3.3

import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[-1, -2, -3],[-4, -5, -6]])

print("matrix A = ", A)
print("matrix B = ", B)
print("matrix A shape == ", A.shape, ", matirx B shape ==", B.shape)
print("matrix A dimension == ", A.ndim, ", matirx B dimension ==", B.ndim)

matrix A =  [[1 2 3]
 [4 5 6]]
matrix B =  [[-1 -2 -3]
 [-4 -5 -6]]
matrix A shape ==  (2, 3) , matirx B shape == (2, 3)
matrix A dimension ==  2 , matirx B dimension == 2


#### Numpy data type

- 데이터 형태 지정하기 : np.array([[...],[...]], **dtype=np.Type**)
- 데이터 형태 확인하기 : object.**dtype**
- 데이터 형태 변환하기 : object.**astype(np.Type)**

### 3.5 넘파이 산술연산


In [26]:
#예제3.4 
#두 행렬 연산 시 대응되는 원소의 개수가 반드시 같아야 한다

import numpy as np

A = np.array([1,2,3])
B = np.array([4,5,6])

print("A==", A, ", B==", B)
print("+ --> ", A+B)
print("- --> ", A-B)
print("* --> ", A*B)
print("/ --> ", A/B)

A== [1 2 3] , B== [4 5 6]
+ -->  [5 7 9]
- -->  [-3 -3 -3]
* -->  [ 4 10 18]
/ -->  [0.25 0.4  0.5 ]


### 3.6 넘파이 형 변환(Reshape)


In [31]:
#예제 3.5

import numpy as np

C = np.array([1,2,3])
print(C.shape)
print(C)

C = C.reshape(1,3)
print(C.shape)
print(C)

D = np.array([[1,2,3],[4,5,6]]) #2*3 형태의 행렬
print(D.shape)
print(D)

D = D.reshape(3,2) #reshape 메서드를 이용해서 3*2 행렬로 변경
print(D.shape)
print(D)

(3,)
[1 2 3]
(1, 3)
[[1 2 3]]
(2, 3)
[[1 2 3]
 [4 5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


C.shape는 메서드를 통해 **1X3 형태의 행렬**을 나타냄 <br>
D.shape는 메서드를 통해 **3X2 형태의 행렬**을 나타냄

- reshape(-1, XXX)
    - 해당 메서드의 두 번째 인수 XXX값으로 주어지는 coloum을 가지는 행렬로 형 변환

In [35]:
#예제 3.6 행렬 형 변환 reshape(-1, ...)

import numpy as np

A= np.array([[1,2,3,4],[10,20,30,40],[100,200,300,400]])
print(A.shape)

#np.reshape(-1,3) 형 변환

B = A.reshape(-1,3)
print("B shape == ", B.shape)
print(B)

#np.reshape(-1,6)

C= A.reshape(-1, 6)
print("C reshape ==", C.shape)
print(C)

(3, 4)
B shape ==  (4, 3)
[[  1   2   3]
 [  4  10  20]
 [ 30  40 100]
 [200 300 400]]
C reshape == (2, 6)
[[  1   2   3   4  10  20]
 [ 30  40 100 200 300 400]]


### 3.7 Numpy Broadcast 넘파이 브로드캐스트

- 행렬의 사칙연산은 기본적으로 두 행렬의 크기가 동일한 경우에만 가능
- **Numpy**에서는 **크기가 다른 행렬**도 사칙연산이 가능하게 할 수 있음 -> Broadcast
- **Broadcast : 차원이 작은 쪽이 큰 쪽에 맞추어 행 단위로 반복적 크기를 확장한다**
    - **단 행렬 곱 연산에는 적용 불가!! 오직 사칙연산만 가능하다**


In [38]:
#예제 3.7

import numpy as np

A = np.array([[1,2], [3,4]]) #행렬 2X2
B = 5                        #스칼라
print(A+B)

C = np.array([[1,2],[3,4]])  #행렬 2X2
D = np.array([4,5])          #행렬 1X2
print(C+D)

[[6 7]
 [8 9]]
[[5 7]
 [7 9]]


### 3.8 넘파이 전치행렬(Transpose)

In [41]:
# 예제 3.8

import numpy as np

A= np.array([[1,2],[3,4],[5,6]])
B= A.T

print("A shape: ", A.shape)
print("B shape: ", B.shape)
print(A)
print(B)

A shape:  (3, 2)
B shape:  (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [46]:
#예제 3.9 

import numpy as np

C = np.array([1,2,3,4,5])
D = C.T

print(C, C.shape)
print(D, D.shape)


E= C.reshape(1,5)
F= E.T

print("Eshape : ", E.shape)
print("Fshape: ", F.shape)

[1 2 3 4 5] (5,)
[1 2 3 4 5] (5,)
Eshape :  (1, 5)
Fshape:  (5, 1)


**Vector 벡터에 Transpose 연산(C.T)을 수행해도 계속 Vector로 남는다**<br>
    : 벡터는 열과 행을 구별하지 않는 1차원이기 때문에<br>
       전치행렬을 만드려고 해도 열과 행을 구분할 수 없기 때문
      
**Vector를 행렬로 전치하고 싶다면?**<br>
   : reshape()를 이용해 강제로 행렬로 변환한 뒤, reshape() 메서드 사용

### 3.9 넘파이 행렬 곱(Matrix Multiplication)

- 행렬 곱 : **np.dot(A, B)** 으로 나타낸다
- 행렬 곱은 **A의 열 column = B의 행 row**가 같아야 가능하다

In [51]:
#예제 3.10

import numpy as np

A= np.array([[1,2,3],[4,5,6]])
B= np.array([[-1,-2],[-3,-4],[-5,-6]])

C= np.dot(A, B)

print("Ashape : ", A.shape, ", Bshape : ", B.shape, ", Cshape : ", C.shape)

print(C)

Ashape :  (2, 3) , Bshape :  (3, 2) , Cshape :  (2, 2)
[[-22 -28]
 [-49 -64]]


### 3.10 행렬 원소 접근(Indexing, Slicing)


In [54]:
# 예제 3.11

import numpy as np

A = np.array([[10,20], [30,40], [50,60]])
print('A.shape = ', A.shape)
print(A)

#[행 인덱스: 열 인덱스] 혼동 주의
print("A[0,0] : ", A[0,0]) # 행의 0 인덱스, 열의 0 인덱스
print("A[2,1] : ", A[2,1]) # 행의 2 인덱스, 열의 1 인덱스
print("A[:0] : ", A[:0]) # 행의 모든 인덱스, 열의 0 인덱스
print("A[0:-1, 1:2] : ", A[0:-1,1:2]) 
# 행의 0인덱스~ -1 인덱스 = 모든 인덱스, 열의 1 인덱스 ~ 2 인덱스
print("A[:,:] : ", A[:,:])
#행의 모든 인덱스, 열의 모든 인덱스


A.shape =  (3, 2)
[[10 20]
 [30 40]
 [50 60]]
A[0,0] :  10
A[2,1] :  60
A[:0] :  []
A[0:-1, 1:2] :  [[20]
 [40]]
A[:,:] :  [[10 20]
 [30 40]
 [50 60]]


- 4번째 출력 값이 [ [20] [40] ] 으로 출력된 이유
    - 단 하나의 원소가 추출되더라도 범위를 지정한 슬라이싱으로 추출되었다는 것을 나타내기 위함

### 3.11 넘파이 이터레이터(Iterator)

- 행렬의 모든 원소를 처음부터 끝까지 하나씩 가져올 때는 **Iterator** 방법을 가장 많이 사용한다.

In [63]:
#3.12 넘파이 이터레이터 사용법

import numpy as np

A = np.array([[10,20,30,40], [50,60,70,80]])      # 행렬 A 생성
it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

#flags=['multi_index'] : iterator 생성 후 반복할때 행렬처럼 (row, column) 형태의 multi_index 형태로 동작
#op_flags = ['readwrite'] : iterator를 R/W 형태로 생성

- 행렬 A에 대한 이터레이터 변수it에 저장
- it는 행렬의 첫 번째 원소를 가리킴 -> 처음부터 끝까지 순차적으로 가리키는 포인터 역할을 수행
- flags=['multi_index'] : 이터레이터 생성 후 반복할 때 행렬처럼 (행, 열) 형태를 가지는 multi_index 형태로 동작하라는 의미
- op_flags=['readwrite']: 이터레이터를 Read/Write 형태로 생성시킨다는 뜻

In [64]:
import numpy as np

A = np.array([[10,20,30,40], [50,60,70,80]])      # 행렬 A 생성
it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:   #it 변수를 이용해 A의 모든 원소 값을 가져옴
    idx = it.multi_index #it 변수를 통해 행렬의 인덱스를 가져옴
    print('index = ', idx, ', value = ', A[idx])  
    it.iternext()        #이터레이터를 증가시켜 행렬의 다음 원소 값을 가리킨다

index =  (0, 0) , value =  10
index =  (0, 1) , value =  20
index =  (0, 2) , value =  30
index =  (0, 3) , value =  40
index =  (1, 0) , value =  50
index =  (1, 1) , value =  60
index =  (1, 2) , value =  70
index =  (1, 3) , value =  80


### 3.12 넘파이 유용한 함수(Useful Function)

- np.random()
- rand()
- np.loadtxt()
- np.max()
- np.argmax()


#### 3.12.(1) np.random.rand()
- 0~1 사이의 임의의 실수 값을 얻고자 할 때 사용하는 넘파이 함수

In [68]:
#예제 3.13

import numpy as np

number1 = np.random.rand(3)   #벡터로 생성 가능
number2 = np.random.rand(1,3) #행렬로 생성 가능
number3 = np.random.rand(3,1)

print("random_number1 ==", number1)
print("random_number2 ==", number2)
print("random_number3 ==", number3)

random_number1 == [0.62580697 0.59794086 0.51698658]
random_number2 == [[0.96627015 0.2513955  0.00149838]]
random_number3 == [[0.10887696]
 [0.12075298]
 [0.53810575]]


#### 3.12.(2) np.max(), np.argmax()
- **np.max()** : 벡터나 행렬의 최댓값을 알기 위해 사용
- **np.argmax()** : 벡터/행렬의 max()값의 인덱스 값을 알려주는 np.argmax() 함수도 제공

In [70]:
import numpy as np

A = np.array([2, 6, 3, 1])

print("np.max(A) = ", np.max(A))
print("np.argmax(A) = ", np.argmax(A))

np.max(A) =  6
np.argmax(A) =  1


#### 3.12.(3) np.loadtxt()
- 분리자로 구분된 파일에서 데이터를 읽어와서 행렬로 리턴해 주는 함수
- np.loadtxt(첫 번째 인수 = 파일의 경로/ 두 번째 인수 = 분리자 / 세 번째 인수 = 데이터 타입)

In [73]:
#import numpy as np

#loaded_data = np.loadtxt('./ch03_test.csv', delimiter=',', dtype=np.float32)

#print('loaded_data.shape=', loaded_data.shape)
#print(loaded_data)