<a href="https://colab.research.google.com/github/lizardnote/bigboonki/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0_ch1_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#데이터셋 불러오기(로컬에서 불러오기)
# from google.colab import files
# uploaded = files.upload()

#링크로 불러오기
# import pandas as pd
# df = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/data/main/mtcars.csv")

#구글드라이브 마운트
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


#ch1. python 기초와 데이터 구조
## 1-1.변수와 연산

In [ ]:
#변수할당
number = 10
greeting = '안녕하세요'

In [ ]:
print(number, greeting)

10 안녕하세요


In [ ]:
number = "HI"

In [ ]:
#데이터 타입 확인
type(number)
#df.column.dtype.

str

# ch1-3 Numpy
### numpy 사용 함수 정리
- np.array([1,2,3])
- np.arange(10)
- np.linspace() : 범위 균등 분할
- np.repeat([1,2,3], 2) : 반복 -> 112233
- np.tile([1,2,3],2) : 벡터 전체 반복 -> 123123
- len(a) : 첫번째 차원의 길이 출력함
- size(a) : 전체 요소 수 구하기
- shape(a) : 차원의 크기
- 슬라이싱
  - a[-1] : 마지막 값
  - a[::2] : 처음부터 끝까지 스텝 2
  - a[1::2] : 1부터 끝까지 스텝 2
- np.delete()
- np.where() : 원소 위치 찾기
- np.mean, np.sum, np.median, np.std
- np.nan
- np.column_stack / row_stack
- up.concatenate()
- np.resize()

In [ ]:
import numpy as np

### Vector 생성하기
- 배열 생성하면서 채우기
- 빈 배열 선언 후 채우기

In [ ]:
a = np.array([1,2,3,4,5])   #numeric vector
b = np.array(['apple', 'banana','orange'])  #string vector
c = np.array([True, False, True, False])    #boolen vector

In [ ]:
print(a)
print(b)
print(c)

[1 2 3 4 5]
['apple' 'banana' 'orange']
[ True False  True False]


np.empty()
np.zeros()

In [ ]:
x = np.empty(3)  #빈 배열 생성
print("빈 벡터 생성 : ", x)

x[0] = 3
x[1] = 5
x[2] = 3
print('채워진 벡터: ',  x)

빈 벡터 생성 :  [3. 5. 3.]
채워진 벡터:  [3. 5. 3.]


In [ ]:
y = np.zeros(3)
print(y)

[0. 0. 0.]


#### 배열 생성하면서 채우기
- np.array() : 함수로 직접 입력
- np.arrange() : 함수를 사용해서 일정한 간격의 숫자 배열 생성
  - start, stop, step, dtype=None / start, step 생략가능
- np.linspace() : 함수를 사용해 지정한 범위를 균일하게 나눈 숫자 배열 생성
  - start, stop, num, endpoint, retstep, dtype

In [ ]:
ar1 = np.arange(10)
ar2 = np.arange(0,2,0.5)

print(ar1)
print(ar2)

[0 1 2 3 4 5 6 7 8 9]
[0.  0.5 1.  1.5]


In [ ]:
linear_space1 = np.linspace(0,1,5)
print(linear_space1)

linear_space2 = np.linspace(0, 1, 5, endpoint = False) #end값 1 미포함으로 계산
print("endpoint 옵션 변경", linear_space2)

[0.   0.25 0.5  0.75 1.  ]
endpoint 옵션 변경 [0.  0.2 0.4 0.6 0.8]


#### 배열 반복하기
- np.repeat(a, repeats, axis=None)
  - a : 반복할 요소, repeats : 반복 횟수, axis = 축 지정
- np.tile(a, reps)
  - a : 반복할 배열, reps : 반복 횟수

In [ ]:
repeated_vals_1 = np.repeat(8,4)
print("repeated 8 four times:", repeated_vals_1)

repeated_vals_2 = np.repeat([1,2,4], 2)   #[1,2,4] 2번 반복
print("repeated 8 four times:", repeated_vals_2)

repeated 8 four times: [8 8 8 8]
repeated 8 four times: [1 1 2 2 4 4]


In [ ]:
repeated_whole = np.tile([1,2,4],2)
print(repeated_whole)

[1 2 4 1 2 4]


#### 벡터의 길이
- len() : 1차원 배열에서는 배열의 요소 / 배열의 첫번째 차원의 길이
- a.shape : 각 차원의 크기를 튜플로 반환
- a.size : 배열의 전체 요소 수

In [ ]:
a = np.array([1,2,3,4,5])
print(len(a))
print(a.shape)
print(a.size)

5
(5,)
5


#### 벡터 슬라이싱
1) 인덱싱

2) 슬라이싱 연산자

3) 논리연산자, 조건문

4) 논리연산자 혼합

5) 필터링을 이용한 벡터 변경

6) 조건을 만족하는 위치 탐색


In [ ]:
np.random.seed(42)
a = np.random.randint(1,21,10)  #랜덤한 int값 추출
print(a)
print(a[1]) #a배열 2번째 값 출력

[ 7 20 15 11  8  7 19 11 11  4]
20


In [ ]:
print(a[2:5])
print(a[[0,2,4]]) #인덱싱 안에 리스트 들어가도 가능

[15 11  8]
[ 7 15  8]


In [ ]:
print(np.delete(a,1))  #index = 1 값 제외하고 출력

[ 7 15 11  8  7 19 11 11  4]


In [ ]:
print(a[[1,1,3,2]]) #index 중복 선택 가능

[20 20 11 15]


In [ ]:
b = a[a>3] #비교 연산을 사용한 벡터 슬라이싱
print(b)

[ 7 20 15 11  8  7 19 11 11  4]


In [ ]:
b = a[(a>2) & (a<9)]
print(b)

[7 8 7 4]


In [ ]:
print(a[a==0])
print(a[a!=0])

[]
[ 7 20 15 11  8  7 19 11 11  4]


In [ ]:
print(~(a==8))
print(a[~(a==8)])

[ True  True  True  True False  True  True  True  True  True]
[ 7 20 15 11  7 19 11 11  4]


In [ ]:
a = np.array([5,10,15,20,25,30])
a[a >= 10] = 10
print(a)

[ 5 10 10 10 10 10]


In [ ]:
b = np.array([5,10,15,20,25,30])
result = a < 11
print(result)

result = np.where(a < 11)
print(result)

[ True  True False False False False]
(array([0, 1]),)


#### numpy 벡터 활용하기

In [2]:
import numpy as np
a = np.array([1,2,3,4,5])

sum_a = np.sum(a)
mean_a = np.mean(a)
median_a = np.median(a)
std_a = np.std(a, ddof = 1)
var_a = np.var(a)

print(sum_a, mean_a, median_a, std_a, var_a)

15 3.0 3.0 1.5811388300841898 2.0


ddof : degree of freedom

#### nan 다루기
- nan은 정의되지 않아 알 수 없는 값을 의미한다.
- np.nan을 벡터에 추가하면 해당 위치에 nan이라는 이상치가 들어감
- nan 과 None은 다르다 **

In [3]:
a = np.array([20, np.nan, 13, 24 ,309])

In [5]:
np.mean(a)

np.float64(nan)

In [6]:
np.nanmean(a)

np.float64(91.5)

In [9]:
value = np.nan
if np.isnan(value):
  print("값이 nan입니다")

값이 nan입니다


In [10]:
value+1  #수치연산은 가능하나 nan으로 출력함

nan

In [14]:
value2 = None
if value2 is None:
  print("none 입니다.")


none 입니다.


In [ ]:
value2 + 1 #수치연산 불가

nan 지우기

In [18]:
a_filtered = a[~np.isnan(a)]  #nan 값 삭제
a_filtered

array([ 20.,  13.,  24., 309.])

벡터 합치기

In [19]:
str_vec = np.array(["사과", "배", "수박", "참외"])
str_vec

array(['사과', '배', '수박', '참외'], dtype='<U2')

In [22]:
mix_vec = np.array(["사과", 12, "수박", "참외"], dtype = str)  #다른 문자 타입이 들어가면 통일할 수 있는 타입으로 변경 후 벡터 저장
mix_vec

array(['사과', '12', '수박', '참외'], dtype='<U2')

- np.concatenate( ) : 벡터 결함
- np.column_stack( ) : 벡터 세로 결합
- np.row_stack( ) : 벡터 가로 결합
- np.resize( ) : 벡터 길이 조정 / 벡터 길이가 다른 경우 오류남 -> resize로 강제로 맞출 수 있음

In [24]:
combine_vec = np.concatenate((str_vec, mix_vec))
combine_vec

array(['사과', '배', '수박', '참외', '사과', '12', '수박', '참외'], dtype='<U2')

In [25]:
combine2_vec = np.column_stack((str_vec, mix_vec))
combine2_vec

array([['사과', '사과'],
       ['배', '12'],
       ['수박', '수박'],
       ['참외', '참외']], dtype='<U2')

In [26]:
combine3_vec = np.row_stack((str_vec, mix_vec))
combine3_vec

<ipython-input-26-2a2ef434848b>:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  combine3_vec = np.row_stack((str_vec, mix_vec))


array([['사과', '배', '수박', '참외'],
       ['사과', '12', '수박', '참외']], dtype='<U2')

In [28]:
vec1 = np.arange(1,5)
vec2 = np.arange(12,18)
vec1 = np.resize(vec1, len(vec2))
vec1

array([1, 2, 3, 4, 1, 2])

In [31]:
uneven_stacked = np.column_stack((vec1, vec2))
uneven_stacked

array([[ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15],
       [ 1, 16],
       [ 2, 17]])

## 연습문제

In [32]:
#1번
a = np.array([1,2,3,4,5])

In [35]:
b = a + 5
b

array([ 6,  7,  8,  9, 10])

In [41]:
#2번
a = np.array([12,21,35,48,5])
b = np.array([a[i] for i in range(len(a)) if i%2 == 0])
b

array([12, 35,  5])

In [52]:
#2번 해설
a = np.array([12,21,35,48,5])
a[::2]

array([12, 35,  5])

In [42]:
#3번
a = np.array([1,22,93,64,54])
max(a)

np.int64(93)

In [47]:
#4번
a = np.array([1,2,3,2,4,5,4,6])
b = np.array([set(a)])
b

array([{np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)}],
      dtype=object)

In [54]:
#4번 해설
a = np.array([1,2,3,2,4,5,4,6])
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [49]:
#5번
a = np.array([21,31,58])
b = np.array([24,44,67])
c = np.empty(6)

for i in range(6):
  if i % 2 == 0:
    c[i] = a[i//2]
  else:
    c[i] = b[i//2]

c

array([21., 24., 31., 44., 58., 67.])

In [55]:
#5번 해설
a = np.array([21,31,58])
b = np.array([24,44,67])
c = np.empty(a.size + b.size, dtype = a.dtype)

c[0::2] = a
c[1::2] = b
c

array([21, 24, 31, 44, 58, 67])

In [50]:
#6번
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9])
c = np.empty(min(len(a),len(b)))

for i in range(min(len(a), len(b))):
  c[i] = a[i] + b[i]
c

array([ 7.,  9., 11., 13.])

In [56]:
#6번 해설
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9])
c = a[:-1] + b
c

array([ 7,  9, 11, 13])

# ch1-4. numpy 행렬과 배열

In [59]:
matrix = np.column_stack((np.arange(1,5), np.arange(12, 16)))
print(matrix)
print(matrix.shape)

[[ 1 12]
 [ 2 13]
 [ 3 14]
 [ 4 15]]
(4, 2)


In [60]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [63]:
y = np.arange(1,5).reshape(2,2)
y

array([[1, 2],
       [3, 4]])

In [3]:
#3차원 배열 합치기
import numpy as np
m1 = np.arange(1,7).reshape(2,3)
m2 = np.arange(7,13).reshape(2,3)
m3 = np.array([m1,m2])
m3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [4]:
m3[0,::]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
m3[:,:,:-1]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [6]:
m3.shape

(2, 2, 3)

In [12]:
m3_t= m3.transpose(0,2,1)

In [19]:
# print(m3_t.mean(axis = 0))
# print(m3_t.mean(axis = 1))
print(m3_t)


[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


In [18]:
print(m3_t.cumsum(axis = 0))
print(m3_t.mean(axis = 1))
print(m3_t)


[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 8 14]
  [10 16]
  [12 18]]]


In [27]:
m3_t.flatten()

array([ 1,  4,  2,  5,  3,  6,  7, 10,  8, 11,  9, 12])

In [24]:
c = np.array([[1,2,3], [4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
c.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
m3_t.clip(2,9)

array([[[2, 4],
        [2, 5],
        [3, 6]],

       [[7, 9],
        [8, 9],
        [9, 9]]])

In [31]:
m3_list = m3_t.tolist()
m3_list

[[[1, 4], [2, 5], [3, 6]], [[7, 10], [8, 11], [9, 12]]]

깊은 복사 진행 시 - d.copy()

#연습문제 - #4

In [33]:
#1
a = np.array([[3,5,7],[2,3,6]])
a

array([[3, 5, 7],
       [2, 3, 6]])

In [48]:
#2
b = np.array([[8,10,7,8],
              [2,4,5,5],
              [7,6,1,7],
              [2,6,8,6],
              [9,3,4,2]])
b_selected = b[[1,3,4],:]
b_selected

array([[2, 4, 5, 5],
       [2, 6, 8, 6],
       [9, 3, 4, 2]])

In [50]:
b_filter = b[b[:,2]>3, :]
b_filter

array([[ 8, 10,  7,  8],
       [ 2,  4,  5,  5],
       [ 2,  6,  8,  6],
       [ 9,  3,  4,  2]])

In [53]:
b_sum = b[np.sum(b, axis = 1) >= 20, : ]
b_sum

array([[ 8, 10,  7,  8],
       [ 7,  6,  1,  7],
       [ 2,  6,  8,  6]])

In [54]:
col_means = np.mean(b,axis = 0)
col_means

array([5.6, 5.8, 5. , 5.6])

In [57]:
#5
col_indiecs = np.where(col_means > 5)[0]
col_indiecs

array([0, 1, 3])

In [59]:
#6
b[np.sum(b > 7, axis = 1) >= 1, :]


array([[ 8, 10,  7,  8],
       [ 2,  6,  8,  6],
       [ 9,  3,  4,  2]])